from boltiot import Bolt, Sms #Import Sms and Bolt class from boltiot library
import json, time, datetime

SID = 'You can find SID in your Twilio Dashboard' 
AUTH_TOKEN = 'You can find  on your Twilio Dashboard' 
FROM_NUMBER = 'This is the no. generated by Twilio. You can find this on your Twilio Dashboard'
TO_NUMBER = 'This is your number. Make sure you are adding +91 in beginning
API_KEY = 'This is your Bolt Cloud accout API key'
DEVICE_ID = 'This is the ID of your Bolt device'

startingHour = int(input("Starting Hour(enter in 24 hour format): "))
endingHour = int(input("Ending Hour(enter in 24 hour format): "))

bolt = Bolt(API_KEY, DEVICE_ID)
sms = Sms(SID, AUTH_TOKEN, TO_NUMBER, FROM_NUMBER)

while True:
    current_time = datetime.datetime.now()  # Current Time

    try:
        if startingHour < current_time.hour < endingHour:
            lightValue = int(json.loads(bolt.digitalWrite('3', 'HIGH'))['value'])
            print(f"Light ON/OFF state {lightValue}")  # Lights On if the time is between the given range

            buzzValue = int(json.loads(bolt.digitalRead('4'))['value'])
            print(f"Buzzer ON/OFF state: {buzzValue}")  # Buzzer On if the time is between the given range
            time.sleep(10)
            if buzzValue == 1 and lightValue == 1:
                bolt.digitalWrite('0', 'HIGH')
                print("Making request to Twilio to send a SMS")
                response = sms.send_sms("An Intuder has breached your home ")  # Message to phone if someone enters home at that time
                time.sleep(10)
        else:
            bolt.digitalWrite('3', 'LOW')
            print("System will work from 12am to 6am")  # Print if beyond the given time range
            time.sleep(10)
    except Exception as e:
        print("Error occurred: Below are the details")
        print(e)
    time.sleep(10)
